# Generated by Django 5.0.4 on 2024-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review_delete_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
