# Generated by Django 5.0.4 on 2024-04-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
