# Generated by Django 5.0.4 on 2024-04-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_review_likes_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
