# Generated by Django 4.2.13 on 2024-06-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cartitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
    ]
