# Generated by Django 4.2.13 on 2024-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_cartitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pizza_type',
            field=models.CharField(default='peperoni', max_length=20),
            preserve_default=False,
        ),
    ]
