# Generated by Django 4.2.13 on 2024-06-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_cartitem_id_cartitem_cart_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_item_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
