# Generated by Django 4.2.13 on 2024-06-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_cartitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
