# Generated by Django 4.2.13 on 2024-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_cartitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=10)),
                ('apartment_number', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('delivery_time', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_items', models.ManyToManyField(related_name='orders', to='main.cartitem')),
            ],
        ),
    ]
