# Generated by Django 4.2.13 on 2024-06-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='house_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
    ]
